default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: root               
  password: "Xz13467980@"    
  host: localhost

development:
  <<: *default
  database: Test1 # 好きなDB名に変更してOK

test:
  <<: *default
  database: Test1        # 好きなDB名に変更してOK

production:
  <<: *default
  database: my_app_production
  username: <%= ENV['MYSQL_USERNAME'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: <%= ENV['MYSQL_HOST'] || 'localhost' %>